name: Windows (MSVC)

on: [push, pull_request]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, Win32]

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2

    - name: Build ${{ matrix.platform }}
      run: |
        $options = @( `
          '-property:Configuration=Release', `
          '-property:Platform=${{ matrix.platform }}', `
          '-maxcpucount', `
          '-verbosity:minimal' `
        )
        & msbuild Windows\VisualStudio\quakespasm.sln $options
        if (-not $?) { throw "Build failed" }
